version: '3'
services:
  nginx:
    image: nginx:latest                 # 镜像`nginx:1.21.1`
    container_name: gpt_nginx               # 容器名为'nginx'
    restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                            # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/conf.d:/etc/nginx/conf.d"
      - "./html:/usr/share/nginx/html"
      - "./log:/var/log/nginx"
      - "./TLS:/usr/share/nginx/TLS"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:                              # 映射端口
      - "12455:80"
      - "12456:443"
      - "12457:444"
     
